name: Product Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      ENVIRONMENT: development
      SECRET_KEY: secret_key
      ENCRYPT_KEY: #$%^&tfgdgjyj)(*&*()PO:LO(*&^%$%^&*()IUYT%$ESDFGH)

  steps:
  - uses: actions/checkout@v4
  - uses: actions/setup-python@v5
    with:
      python-version: 3.10.5

  -run: python -m pip install --upgrade pip
  -run: pip install -r requirements.txt
  -run: python manage.py migrate
  -run: python manage.py test

